import NavbarMenu from '@/components/navbar/navbarMenu';
import clsx from 'clsx';
import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import './globals.css';

const vazirmatn = Vazirmatn({
  variable: '--font-vazirmatn',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'سعید توازانی',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={clsx(vazirmatn.variable, 'antialiased')}>
        <NavbarMenu />
        {children}
      </body>
    </html>
  );
}
